# Assignment 7.1: Data Preprocessing

**Name:** Umang Patel  
**Course:** AIT 620: Methods of Artificial Intelligence and Machine Learning  
**Professor:** Dr. Fuat Akal  
**Date:** October 15, 2026

In this assignment I clean the United Nations data on immigration to Canada from 1980 to 2013 so it is easier to read and use.

In [1]:
import pandas as pd

The data is in the sheet called **Canada by Citizenship**. The first 20 rows of the sheet are title information and the last 2 rows are totals, so I skip them when reading the file.

In [2]:
# read the data and skip the title rows at the top and the total rows at the bottom
df_can = pd.read_excel('Canada.xlsx',
                       sheet_name='Canada by Citizenship',
                       skiprows=range(20),
                       skipfooter=2)

df_can.head()

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1

The columns AREA, REG and DEV are only number codes, and Type and Coverage are almost the same for every country, so I remove them.

In [3]:
# remove the columns we do not need
df_can.drop(['AREA', 'REG', 'DEV', 'Type', 'Coverage'], axis=1, inplace=True)

Next I give some columns clearer names and change all column names to text, since the years are numbers.

In [4]:
# rename the columns
df_can.rename(columns={'OdName': 'Country', 'AreaName': 'Continent', 'RegName': 'Region'}, inplace=True)

# make all column names text
df_can.columns = list(map(str, df_can.columns))

Then I use the country name as the index and add a Total column with the sum of all years from 1980 to 2013.

In [5]:
# set Country as the index
df_can.set_index('Country', inplace=True)

# add the total for each country
years = list(map(str, range(1980, 2014)))
df_can['Total'] = df_can[years].sum(axis=1)

df_can.head()

,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,1986,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,496,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,1,...,1223,856,702,560,716,561,539,620,603,15699
Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,69,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,2,...,0,1,1,0,0,0,0,1,1,15

The final table has one row for each of the 195 countries, with the continent, region, development level, the number of immigrants for each year, and the total.